language: python
python:
  # CPython: https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
cache: pip
before_install:
  - bin/prepare
script:
  - bin/test
  - bin/deploy
env:
  global:
    - K8S_VERSION="1.6.2"
    - K8S_NAMESPACE="delivery-pro"
    - K8S_CLUSTER="schip-prod01"
    - secure: "REMOVED"
