language: python
python:
  - '3.6'
sudo: required
services:
- docker
cache: pip
install:
  - bin/install && echo 'test'
env:
  global:
  - DOCKER_USERNAME=captainfiaas
  - DOCKER_PASSWORD=not_set
script:
  - tox
  - bin/docker_build
after_success: tox -e coverage
deploy:
  provider: script
  script: bin/docker_push
  skip_cleanup: true
  on:
    branch: master
