schema: '1'
id: fiaas-mast

metadata:
  name: Deploy fiaas-mast application
  description: Deploy fiaas-mast to delivery-dev and delivery-pro in schip-prod01 and schip-prod02
  owner: platform-delivery@schibsted.com

variables:
- name: notifySlackChannel
  description: Slack channel to notify about manual judgement
  type: string
  defaultValue: paas-internal

- name: namespaceDev
  description: Development namespace
  type: string
  defaultValue: delivery-dev

- name: namespacePro
  description: Production namespace
  type: string
  defaultValue: delivery-pro

- name: schipProd02ApiserverHost
  description: Apiserver hostname for the schip-prod02 cluster
  type: string
  defaultValue: "https://schip.cre-pro.schibsted.io"

- name: schipProd01ApiserverHost
  description: Apiserver hostname for the schip-prod01 cluster
  type: string
  defaultValue: "https://api.prod01.eu-west-1.admin.cre-pro.schibsted.io"

- name: schipProd02K8sVersion
  description: Kubernetes version of the schip-prod02 cluster
  type: string
  defaultValue: "v1.6.13"

- name: schipProd01K8sVersion
  description: Kubernetes version of the schip-prod01 cluster
  type: string
  defaultValue: "v1.9.6"

stages:
- id: deployDeliveryDevProd02
  type: partial.DeployWithHelmOnTravis
  config:
    namespace: "{{ namespaceDev }}"
    apiserverHost: "{{ schipProd02ApiserverHost }}"
    k8sVersion: "{{ schipProd02K8sVersion }}"

- id: deployDeliveryDevProd01
  type: partial.DeployWithHelmOnTravis
  config:
    namespace: "{{ namespaceDev }}"
    apiserverHost: "{{ schipProd01ApiserverHost }}"
    k8sVersion: "{{ schipProd01K8sVersion }}"

- id: manualJudgment
  type: manualJudgment
  config:
    sendNotifications: "true"
    notifications:
      - type: slack
        address: "{{ notifySlackChannel }}"
        when:
          - manualJudgement
          - manualJudgmentContinue
          - manualJudgmentStop
  dependsOn:
    - deployDeliveryDevProd01
    - deployDeliveryDevProd02

- id: deployDeliveryProProd02
  type: partial.DeployWithHelmOnTravis
  config:
    namespace: "{{ namespacePro }}"
    apiserverHost: "{{ schipProd02ApiserverHost }}"
    k8sVersion: "{{ schipProd02K8sVersion }}"

  dependsOn:
    - manualJudgment

- id: deployDeliveryProProd01
  type: partial.DeployWithHelmOnTravis
  config:
    namespace: "{{ namespacePro }}"
    apiserverHost: "{{ schipProd01ApiserverHost }}"
    k8sVersion: "{{ schipProd01K8sVersion }}"
  dependsOn:
    - manualJudgment

partials:
- id: DeployWithHelmOnTravis
  usage: Deploy using Helm with Travis
  variables:
  - name: namespace
    description: The Kubernetes namespace to deploy to
  - name: apiserverHost
    description: The Kubernetes apiserver host to execute the deployment via
  - name: k8sVersion
    description: The Kubernetes version to deploy to (used to determine which kubectl version to use)
  stages:
  - id: deployHelm
    type: travis
    name: "Deploy to {{ namespace }}"
    config:
      job: "spt-infrastructure/fiaas-mast"
      master: "travis-schibsted"
      parameters:
        HELM_DEPLOY: "true"
        K8S_NAMESPACE: "{{ namespace }}"
        K8S_HOST: "{{ apiserverHost }}"
        K8S_VERSION: "{{ k8sVersion }}"
        IMAGE_TAG: "${trigger.buildInfo.artifacts.?[type == 'docker].?[name matches 'containers.schibsted.io/spt-infrastructure/fiaas-mast:.+'].![reference][0]}"
      continuePipeline: false
      failPipeline: true
