apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: schip-spinnaker-webhook
  labels:
    app: schip-spinnaker-webhook
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: schip-spinnaker-webhook
    spec:
      containers:
        - name: schip-spinnaker-webhook
          image: "containers.schibsted.io/schip-spinnaker-webhook:${CONTAINER_TAG}"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5000
            name: http
            protocol: TCP
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
#          livenessProbe:
#            httpGet:
#              path: /index.php
#              port: http
#              httpHeaders:
#              - name: Host
#                value: {{ include "host" . | quote }}
#            initialDelaySeconds: 180
#            timeoutSeconds: 5
#            failureThreshold: 6
#          readinessProbe:
#            httpGet:
#              path: /index.php
#              port: http
#              httpHeaders:
#              - name: Host
#                value: {{ include "host" . | quote }}
#            initialDelaySeconds: 30
#            timeoutSeconds: 3
#            periodSeconds: 5
