apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: schip-spinnaker-webhook
  labels:
    app: schip-spinnaker-webhook
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: schip-spinnaker-webhook
    spec:
      containers:
        - name: schip-spinnaker-webhook
          image: "containers.schibsted.io/spt-infrastructure/schip-spinnaker-webhook:${CONTAINER_TAG}"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: ${CONTAINER_PORT}
            name: http
            protocol: TCP
          env:
          - name: PORT
            value: "${CONTAINER_PORT}"
          - name: DEBUG
            value: "${DEBUG}"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 2
