replicaCount: 2

image:
  repository: "containers.schibsted.io/spt-infrastructure/fiaas-mast"
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: nginx
  type: ClusterIP
  externalPort: 80

ingress:
  host: "fiaas-mast.ingress.local"
  whitelistSourceRange: ""
  enableTLS: false

besteffortQoS: false # if set to true, will force BestEffort QoS by not setting any resource limits or requests, even if these values are  specified

annotations: {} # can be used to set custom annotations on every resource

secrets: # Must be set by user
  artifactoryUser: replace_me
  artifactoryPassword: replace_me
