apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-secret"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  heimdall_token: {{ .Values.secrets.token | b64enc | quote }}
