apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        prometheus.io/path: /_/metrics
        prometheus.io/port: http
        prometheus.io/scrape: "true"
        {{- range $key, $value := .Values.annotations }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      containers:
      - name: {{ template "name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 2
        env:
        - name: PORT
          value: "5000"
        - name: DEBUG
          value: "${DEBUG}"
        - name: ARTIFACTORY_USER
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-secret
              key: artifactory_user
        - name: ARTIFACTORY_PWD
          valueFrom:
            secretKeyRef:
              name: {{.Release.Name}}-secret
              key: artifactory_password
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

{{- if not .Values.besteffortQoS }}
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
{{- end }}
