apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    kubernetes.io/ingress.class: nginx
{{- if eq .Values.ingress.host "fiaas-mast.ingress.cre-pro.schibsted.io" }}
    kubernetes.io/tls-acme: "true"
{{- else }}
    certmanager.k8s.io/cluster-issuer: "letsencrypt"
{{- end}}
    ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelistSourceRange }}
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: http
          - path: /heimdall-token
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: heimdall

{{- if eq .Values.ingress.host "fiaas-mast.ingress.cre-pro.schibsted.io" }}
    - host: fiaas-mast.ingress.prod02.cre-pro.schibsted.io
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: http
          - path: /heimdall-token
            backend:
              serviceName: {{ template "fullname" . }}
              servicePort: heimdall
{{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
{{- if eq .Values.ingress.host "fiaas-mast.ingress.cre-pro.schibsted.io" }}
    - fiaas-mast.ingress.prod02.cre-pro.schibsted.io
{{- end }}
    secretName: {{ template "fullname" . }}
