apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-secret"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.annotations }}
  annotations:
    {{- range $key, $value := .Values.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  heimdall_token: {{ .Values.secrets.token | b64enc | quote }}
  artifactory_user: {{ .Values.secrets.artifactoryUser | b64enc | quote }}
  artifactory_password: {{ .Values.secrets.artifactoryPassword | b64enc | quote }}
